LOGICAL FUNCTION RT_CLEAR_FILE(RT, IOS, IOERR)
	
	implicit none;
	
	!!! VARIÁVEIS DE ENTRADA/SAÍDA
	type(RAMTXT), intent(INOUT) :: RT;
	integer, intent(INOUT) :: IOS;
	character(len=*), intent(INOUT) :: IOERR;
	
	!!! VARIÁVEIS INTERNAS
	
	!!! INÍCIO DA FUNÇÃO !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	
	!!! PRESSUPOR RODADA MAL-SUCEDIDA
	RT_CLEAR_FILE = .FALSE.;
	
	!!! DEALOCAR PARTE A PARTE
	DEALLOCATE (RT%PATH, STAT=IOS, ERRMSG=IOERR);
	IF (IOS .NE. 0) RETURN;
	
	DEALLOCATE (RT%STRING, STAT=IOS, ERRMSG=IOERR);
	IF (IOS .NE. 0) RETURN;
	
	DEALLOCATE (RT%IDX, STAT=IOS, ERRMSG=IOERR);
	IF (IOS .NE. 0) RETURN;
	
	RT%LAST_LINE_READ = 0;
	
	!!! FIM DE DESTRUÇÃO. RODADA BEM SUCEDIDA.
	RT_CLEAR_FILE = .TRUE.;
	
END FUNCTION RT_CLEAR_FILE
